# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:8.1.2

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-input-http